/**
 * Gravitas 3D Headquarters — Station Definitions & Metadata
 * Truthful prototype station models for Wave 12B without fake runtime activity.
 */

import type { StationDefinition, StationId } from '../types.js'

export const STATION_DEFINITIONS: Record<StationId, StationDefinition> = {
  'planning-table': {
    id: 'planning-table',
    name: 'Mission Planning Table',
    roomId: 'MISSION_CONTROL',
    position: [-4.5, 0.0, 5.5],
    rotationY: 0,
    role: 'Goal Ingestion & DAG Decomposition',
    status: 'Operational Foundation',
    description: 'Central architectural light table for DAG planning. Runtime task binding begins Wave 12C+.',
  },
  'codex-workstation': {
    id: 'codex-workstation',
    name: 'Codex Workstation 01',
    roomId: 'AGENT_OPERATIONS',
    position: [-6.5, 0.0, 1.2],
    rotationY: 0,
    role: 'Engineering Specialist',
    status: 'Prototype Workstation',
    description: 'Assigned drafting station for Codex. Runtime isolated worktree binding begins Wave 12C+.',
  },
  'fcc-workstation': {
    id: 'fcc-workstation',
    name: 'Claude / FCC Workstation 02',
    roomId: 'AGENT_OPERATIONS',
    position: [-1.8, 0.0, 1.2],
    rotationY: 0,
    role: 'Architectural Reasoning',
    status: 'Prototype Workstation',
    description: 'Assigned drafting station for FCC / Claude. Runtime isolated worktree binding begins Wave 12C+.',
  },
  'expansion-bay-3': {
    id: 'expansion-bay-3',
    name: 'Expansion Bay 03',
    roomId: 'AGENT_OPERATIONS',
    position: [-6.5, 0.0, -2.4],
    rotationY: 0,
    role: 'Design & Dynamic Agents',
    status: 'Standby Capacity',
    description: 'Modular expansion workstation for Astra or concurrent worker instances.',
  },
  'expansion-bay-4': {
    id: 'expansion-bay-4',
    name: 'Expansion Bay 04',
    roomId: 'AGENT_OPERATIONS',
    position: [-1.8, 0.0, -2.4],
    rotationY: 0,
    role: 'Dynamic Worker Slot',
    status: 'Standby Capacity',
    description: 'Modular expansion bay reserved for high-concurrency DAG execution.',
  },
  'verifier-console': {
    id: 'verifier-console',
    name: 'Verification Console',
    roomId: 'VERIFICATION_LAB',
    position: [6.0, 0.1, 6.5],
    rotationY: 0,
    role: 'Independent Evidence Gate',
    status: 'Cleanroom Prototype',
    description: 'Independent verification terminal for deterministic test execution and mutation scope enforcement.',
  },
  'browser-qa-matrix': {
    id: 'browser-qa-matrix',
    name: 'Device Matrix Wall',
    roomId: 'BROWSER_QA_LAB',
    position: [6.2, 0.1, -0.5],
    rotationY: 0,
    role: 'Playwright DOM Validation',
    status: 'Matrix Bench',
    description: 'Deterministic multi-viewport testing bench for real DOM inspection and visual assertions.',
  },
  'omniroute-rack': {
    id: 'omniroute-rack',
    name: 'OmniRoute Gateway Rack',
    roomId: 'INFRASTRUCTURE_ROOM',
    position: [-8.8, 0.0, -5.8],
    rotationY: 0,
    role: 'Inference Infrastructure',
    status: 'Gateway Active',
    description: 'Dual 42U server cabinet routing model invocations with fallback telemetry. Strictly infrastructure.',
  },
  'approval-plinth': {
    id: 'approval-plinth',
    name: 'Approval Plinth',
    roomId: 'APPROVAL_MEZZANINE',
    position: [0.0, 2.95, 8.5],
    rotationY: 0,
    role: 'Human Authority Station',
    status: 'Awaiting Candidate',
    description: 'Elevated command plinth where candidate commits halt for explicit human authorization.',
  },
  'repository-vault': {
    id: 'repository-vault',
    name: 'Repository Vault Dock',
    roomId: 'VERIFICATION_LAB',
    position: [10.2, 0.1, 4.0],
    rotationY: 0,
    role: 'Base Branch Materialization',
    status: 'Git Archive Dock',
    description: 'Sleek terminal dock where approved commits are materialized into the primary base branch.',
  },
  'dispatch-console': {
    id: 'dispatch-console',
    name: 'Personal OS Dispatch Console',
    roomId: 'INFRASTRUCTURE_ROOM',
    position: [-6.8, 0.0, -4.5],
    rotationY: Math.PI / 4,
    role: 'Background Job Dispatch & Kernel Scheduler',
    status: 'Operational Kernel',
    description: 'Deterministic Background Job Execution Console. Dispatches cron, interval, and one-time tasks with zero persistent inference loops.',
  },
}
